# Created by Unium on 21.02.26
# 
# !! This file was generated by ChatGPT !!
# I use a custom build system which most people
# obviously don't have. This Makefile is there
# just so others can build and use this as well.
#
# Because of this, this Makefile may be outdated.
#
# # Prompt:
# ---
# Convert this file into a Makefile:
# [cat ./project.buildr]
# [ls -R src]
# ---
#
#  My lazy ass was not making a Makefile bruh
#  TODO: replace this AI generated file

TARGET_NAME  := llm
BUILD_DIR    := make-build
TARGET       := $(BUILD_DIR)/$(TARGET_NAME)
CXX          := g++
CXX_STANDARD := -std=c++17
SRC_DIR      := src
INC_FLAGS    := -I$(SRC_DIR)
BUILD        ?= release
COMMON_FLAGS := -pthread

ifeq ($(BUILD), debug)
    CXXFLAGS := -g -Wall -Wextra $(COMMON_FLAGS)
    LDFLAGS  := $(COMMON_FLAGS)
    DEFINES  := 
else
    CXXFLAGS := -Wall -Wextra -O3 -ffast-math -march=native -flto -funroll-loops $(COMMON_FLAGS)
    LDFLAGS  := -flto $(COMMON_FLAGS)
    DEFINES  := -DNDEBUG
endif

SRCS := $(shell find $(SRC_DIR) -name "*.cpp")
OBJS := $(SRCS:%.cpp=$(BUILD_DIR)/%.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	@echo "Linking: $@"
	@$(CXX) $(CXX_STANDARD) $(OBJS) -o $(TARGET) $(LDFLAGS)

$(BUILD_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	@echo "Compiling: $<"
	@$(CXX) $(CXX_STANDARD) $(CXXFLAGS) $(DEFINES) $(INC_FLAGS) -c $< -o $@

clean:
	@echo "Cleaning up..."
	rm -rf $(BUILD_DIR)

info:
	@echo "Build Mode:   $(BUILD)"
	@echo "Binary:       $(TARGET)"
	@echo "Source Files: $(SRCS)"
	@echo "Object Files: $(OBJS)"

.PHONY: all clean info
